New Questionnaire Item: Screen Size
TheFragebogen/TheFragebogen pull request #53
Opened 2019-05-06 12:00 UTC by konnykonny50

This module implements a questionnaire item to determine the screen size of the current TheFragebogen site. It reports the size as an array [width, height] in pixels.

2019-05-06 21:04 UTC, dennisguse requested changes
Approach would work quite nicely.

One really awesome improvement would be to listen for the window.onresize-events.
In this way all changes could be recorded including the timestamp.
Then the data really represents what happened.

https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event

What do you think?

2019-05-06 21:04 UTC, dennisguse commented on src/questionnaireitem_system_screen_size.js
> +A QuestionnaireItemSystem that stores the size of the screen.
the dimensions of the window.

2019-05-06 21:04 UTC, dennisguse commented on src/questionnaireitem_system_screen_size.js
> +@class QuestionnaireItemSystemScreenSize
Please rename to QuestionnaireItemSystemWindowSize

`Screen` is already used in TheFragebogen and might thus be confusing.

2019-05-06 21:04 UTC, dennisguse commented on src/questionnaireitem_system_screen_size.js
> +    QuestionnaireItemSystem.call(this, null, "Screensize", false);
rename

2019-05-06 21:04 UTC, dennisguse commented on src/questionnaireitem_system_screen_size.js
> +    var width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
This is technically possible, but you don't know when getAnswer() is actually called.
It actually happens, when the screenController collects the data on request by a ScreenWaitData.
So all QuestionnaireItemSystemWindow would report the same value.

So, I would recommend reacting on createUI().
And it is also important to document this...
Or you could make it configurable - or report both (ie. createUI() and releaseUI()).

2019-05-06 21:04 UTC, dennisguse commented on src/questionnaireitem_system_screen_size.js
> +    return [width, height];
It is problematic that you might report three different values depending on the browser.
If this is necessary (due to browser differences), I would recommend also reporting the data source.
So, you know what kind of measurement you got.

2019-05-06 21:04 UTC, dennisguse commented on src/questionnaireitem_system_screen_size.js
> +A QuestionnaireItemSystem that stores the size of the screen.
Please document how the data is actually derived.
This might vary quite...
https://ryanve.com/lab/dimensions/

And the derived values might be misleading, if TheFragebogen is not executed in full window (eg., some other content is shown around) - it is not the size of the `Screen`'s area...

2019-05-08 07:44 UTC, konnykonny50 commented on src/questionnaireitem_system_screen_size.js
> +    var width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
I would prefer having it inside createUI() too. But I'm not sure if releaseUI() or the previously mentioned tracking of all changes is overkill.

2019-05-08 20:06 UTC, dennisguse requested changes
Nitpicking

2019-05-08 20:06 UTC, dennisguse commented on src/questionnaireitem_system_viewport_size.js
> +Reports the viewport as array [document.documentElement.clientWidth, document.documentElement.clientHeight] in pixels. It gets measured at the time of createUI().
One sentence per line.

2019-05-08 20:08 UTC, dennisguse commented on src/questionnaireitem_system_viewport_size.js
> +Reports the viewport as array [document.documentElement.clientWidth, document.documentElement.clientHeight] in pixels. It gets measured at the time of createUI().
One nitpicking I forgot: can you also update examples/developer_template.html?
The new JS file needs to be included.

2019-05-09 08:44 UTC, dennisguse approved these changes

2019-05-09 08:46 UTC, merged